### ISSUE TITLE
Node 12 actions deprecated

### ISSUE THREAD

**Issue by mackenziekbrooks** [tameney22/search-index-action#2]
Hey Yoseph, we're getting some errors when updating the site. 1) Node.js 12 actions are deprecated. Update actions to use Node.js 16 and  2) the 'set-output' command is deprecated and will be disabled soon. 

If these are quick fixes for you, great! But will work to move this action over to our accounts. I think I can figure things out.

**Comment by tameney22** [comment]
Just updated the node version and the code's dependencies. I reran the job where you saw the output, and it's looking good now :)
